name: Build documentation

on:
  # push:
  #   branches:
  #     # This should match the DOC3_BRANCH value in the gaussdb-website Makefile
  #     - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs build
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: gaussdb/gaussdb-website
          event-type: gaussdb-commit
          token: ${{ secrets.ACCESS_TOKEN }}
