name: Lint

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    if: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install packages to tests
        run: |
          pip install ./tools/isort-gaussdb/
          pip install ./gaussdb[dev,test]
          pip install ./gaussdb_pool
          pip install types-polib
          pip install pre-commit

      - name: Lint codebase
        run: pre-commit run -a --color=always

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages for async_to_sync
        run: |
            pip install ./tools/isort-gaussdb/
            pip install ./gaussdb[dev,test]
            pip install ./gaussdb_pool
            pip install types-polib

      - name: Check for sync/async inconsistencies
        run: ./tools/async_to_sync.py --check $(find tests -name "*_async.py" -type f ! -path "tests/pq/test_async.py")

      - name: Install requirements to generate docs
        run: sudo apt-get install -y libgeos-dev

      - name: Install Python packages to generate docs
        run: |
            pip install furo
            pip install ./tools/isort-gaussdb/
            pip install ./gaussdb[dev,test]
            pip install ./gaussdb_pool
            pip install types-polib

      - name: Check documentation
        run: sphinx-build -W -T -b html docs docs/_build/html
